### ISSUE TITLE
ImportError: cannot import name 'Parser'

### ISSUE THREAD

**Issue by scorpionipx** [johnlinp/pdf-to-markdown#21]
```
Traceback (most recent call last):
  File "C:\Python36\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Python36\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Python36\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Python36\lib\site-packages\pdf2md\__init__.py", line 1, in <module>
    from parser import Parser
ImportError: cannot import name 'Parser'
```

**Comment by sebastianwindeck** [comment]
I have got a similar issue:

`from parser import Parser`

`ImportError: cannot import name 'Parser' from 'parser' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/parser.cpython-37m-darwin.so)`

**Comment by sebastianwindeck** [comment]
@scorpionipx do you have any update on this?

**Comment by scorpionipx** [comment]
@sebastianwindeck 
Sorry, I didn't try any further.

**Comment by okpatil4u** [comment]
I am having same issue. 

```
Traceback (most recent call last):
  File "/Users/anaconda3/bin/pdf2md", line 5, in <module>
    import pdf2md
  File "/Users/anaconda3/lib/python3.7/site-packages/pdf2md/__init__.py", line 1, in <module>
    from parser import Parser
ImportError: cannot import name 'Parser' from 'parser' (/Users/anaconda3/lib/python3.7/lib-dynload/parser.cpython-37m-darwin.so)
```
