### ISSUE TITLE
Can't convert my pdf doc

### ISSUE THREAD

**Issue by joncodo** [johnlinp/pdf-to-markdown#7]
I need this for work and can help you with this repo if you like. :)

```
Parsing /Users/jodonnell/Desktop/MyFile.pdf
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main(sys.argv)
  File "main.py", line 15, in main
    parser = pdf2md.Parser(filename)
  File "/Users/jodonnell/Code/3rdParty/new/pdf2md/parser.py", line 14, in __init__
    self._document = self._read_file(filename)
  File "/Users/jodonnell/Code/3rdParty/new/pdf2md/parser.py", line 45, in _read_file
    document = PDFDocument(parser)
  File "/Library/Python/2.7/site-packages/pdfminer/pdfdocument.py", line 575, in __init__
    self._initialize_password(password)
  File "/Library/Python/2.7/site-packages/pdfminer/pdfdocument.py", line 598, in _initialize_password
    raise PDFEncryptionError('Unknown algorithm: param=%r' % param)
pdfminer.pdfdocument.PDFEncryptionError: Unknown algorithm: param={u'CF': {u'StdCF': {u'Length': 16, u'CFM': /V2, u'AuthEvent': /DocOpen}}, u'O': '\x0cr\x00O\xda\x01#0\xf0?<\x17B\xac \xaa\xb7=\x14\xa2\x91\xf5\xc5>(\xdc\xdc\x9b\xd6t\xb3\xb1', u'Filter': /Standard, u'P': -1324, u'Length': 128, u'R': 4, u'U': '$\xd8\x8d`\x1802\xc4\xc4\x19:bM\xf5/4\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', u'V': 4, u'StmF': /StdCF, u'StrF': /StdCF}
```

**Comment by joncodo** [comment]
Unfortunately, I can't give you the file :(

**Comment by johnlinp** [comment]
Does your pdf file contains non-English characters? Like "你", "й", "선"?
